// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-AokEUYE1hTRD2J43UHBocYdByt-5pgE',
    appId: '1:349624183674:web:89f4c9bb4381c4756d04c3',
    messagingSenderId: '349624183674',
    projectId: 'test-projct1',
    authDomain: 'test-projct1.firebaseapp.com',
    storageBucket: 'test-projct1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7hF5JkzsqJQ8W-J3FH0R8yzhzQIUAcdA',
    appId: '1:349624183674:android:01eb98755445790f6d04c3',
    messagingSenderId: '349624183674',
    projectId: 'test-projct1',
    storageBucket: 'test-projct1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmaijFt8Y35W8zTSnyFfss4qcwrP8oMGM',
    appId: '1:349624183674:ios:61cd1e7d363d3a1c6d04c3',
    messagingSenderId: '349624183674',
    projectId: 'test-projct1',
    storageBucket: 'test-projct1.appspot.com',
    iosBundleId: 'com.example.flutterSupabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmaijFt8Y35W8zTSnyFfss4qcwrP8oMGM',
    appId: '1:349624183674:ios:61cd1e7d363d3a1c6d04c3',
    messagingSenderId: '349624183674',
    projectId: 'test-projct1',
    storageBucket: 'test-projct1.appspot.com',
    iosBundleId: 'com.example.flutterSupabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-AokEUYE1hTRD2J43UHBocYdByt-5pgE',
    appId: '1:349624183674:web:f91f13fff8a2f8216d04c3',
    messagingSenderId: '349624183674',
    projectId: 'test-projct1',
    authDomain: 'test-projct1.firebaseapp.com',
    storageBucket: 'test-projct1.appspot.com',
  );
}
